/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as JoinIdRouteImport } from './routes/join/$id'
import { Route as PlayIdRouteRouteImport } from './routes/play.$id/route'

const NewIndexRoute = NewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIdRoute = JoinIdRouteImport.update({
  id: '/join/$id',
  path: '/join/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIdRouteRoute = PlayIdRouteRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/play/$id': typeof PlayIdRouteRoute
  '/join/$id': typeof JoinIdRoute
  '/': typeof homeIndexRoute
  '/new/': typeof NewIndexRoute
}
export interface FileRoutesByTo {
  '/play/$id': typeof PlayIdRouteRoute
  '/join/$id': typeof JoinIdRoute
  '/': typeof homeIndexRoute
  '/new': typeof NewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/play/$id': typeof PlayIdRouteRoute
  '/join/$id': typeof JoinIdRoute
  '/(home)/': typeof homeIndexRoute
  '/new/': typeof NewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/play/$id' | '/join/$id' | '/' | '/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/play/$id' | '/join/$id' | '/' | '/new'
  id: '__root__' | '/play/$id' | '/join/$id' | '/(home)/' | '/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlayIdRouteRoute: typeof PlayIdRouteRoute
  JoinIdRoute: typeof JoinIdRoute
  homeIndexRoute: typeof homeIndexRoute
  NewIndexRoute: typeof NewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$id': {
      id: '/join/$id'
      path: '/join/$id'
      fullPath: '/join/$id'
      preLoaderRoute: typeof JoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PlayIdRouteRoute: PlayIdRouteRoute,
  JoinIdRoute: JoinIdRoute,
  homeIndexRoute: homeIndexRoute,
  NewIndexRoute: NewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
