/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PlayIdRouteRouteImport } from './routes/play.$id/route'
import { Route as AppNewIndexRouteImport } from './routes/_app/new/index'
import { Route as ApphomeIndexRouteImport } from './routes/_app/(home)/index'
import { Route as AppJoinIdRouteImport } from './routes/_app/join/$id'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIdRouteRoute = PlayIdRouteRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNewIndexRoute = AppNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApphomeIndexRoute = ApphomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJoinIdRoute = AppJoinIdRouteImport.update({
  id: '/join/$id',
  path: '/join/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ApphomeIndexRoute
  '/play/$id': typeof PlayIdRouteRoute
  '/join/$id': typeof AppJoinIdRoute
  '/new/': typeof AppNewIndexRoute
}
export interface FileRoutesByTo {
  '/play/$id': typeof PlayIdRouteRoute
  '/join/$id': typeof AppJoinIdRoute
  '/': typeof ApphomeIndexRoute
  '/new': typeof AppNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/play/$id': typeof PlayIdRouteRoute
  '/_app/join/$id': typeof AppJoinIdRoute
  '/_app/(home)/': typeof ApphomeIndexRoute
  '/_app/new/': typeof AppNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play/$id' | '/join/$id' | '/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/play/$id' | '/join/$id' | '/' | '/new'
  id:
    | '__root__'
    | '/_app'
    | '/play/$id'
    | '/_app/join/$id'
    | '/_app/(home)/'
    | '/_app/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PlayIdRouteRoute: typeof PlayIdRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/new/': {
      id: '/_app/new/'
      path: '/new'
      fullPath: '/new/'
      preLoaderRoute: typeof AppNewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/(home)/': {
      id: '/_app/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ApphomeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/join/$id': {
      id: '/_app/join/$id'
      path: '/join/$id'
      fullPath: '/join/$id'
      preLoaderRoute: typeof AppJoinIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppJoinIdRoute: typeof AppJoinIdRoute
  ApphomeIndexRoute: typeof ApphomeIndexRoute
  AppNewIndexRoute: typeof AppNewIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppJoinIdRoute: AppJoinIdRoute,
  ApphomeIndexRoute: ApphomeIndexRoute,
  AppNewIndexRoute: AppNewIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PlayIdRouteRoute: PlayIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
